### ISSUE TITLE
Error running in window

### ISSUE THREAD

**Issue by AD20172017** [sam007961/FastMassSpring#10]
I'm editing your code on window platform, and it doesn't work at all after installing the dependency. Can you provide a system image file to run the project?

**Comment by sam007961** [comment]
Can you share the

**Comment by sam007961** [comment]
Can you please share the error you are getting? The project should be buildable on windows with Cmake, the instructions are in the readme.

**Comment by AD20172017** [comment]
My English is not well，some parts may be poorly expressed.
I modified the cmakelists file so that he can locate the glew library.

> #find OpenGL, GLUT, GLEW

> set(GLEW_INCLUDE_DIRS "C:/Users/17656/Desktop/mylearning/include/GL/glew.h") 
> set(GLEW_LIBRARIES "C:/Users/17656/Desktop/mylearning/lib/glew32s.lib")
> find_package(OpenGL REQUIRED)
> find_package(GLUT REQUIRED)
> #find_package(GLEW REQUIRED)
> include_directories(${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIR} ${GLEW_INCLUDE_DIRS})`

And it worked.

> \FastMassSpring\b> cmake ..

> -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22621.
> -- Standard libraries to link to explicitly: none
> -- Found unsuitable Qt version "5.9.7" from C:/Users/17656/anaconda3/Library/bin/qmake.exe
> -- The Fortran compiler identification is unknown
> -- Found unsuitable Qt version "5.9.7" from C:/Users/17656/anaconda3/Library/bin/qmake.exe
> -- Qt4 not found, so disabling the mandelbrot and opengl demos
> -- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
> --
> -- Configured Eigen 3.4.90
> --
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> 
> ************************************************************
> * VCI Buildsystem                                          *
> *                                                          *
> * Package : OpenMesh                                       *
> * Version : 10.0.0                                         *
> ************************************************************
> -- GLM: Version 0.9.9.9
> -- Up-to-date: C:/Users/17656/Desktop/class/GAMES101/FastMassSpring/b/shaders/
> -- Up-to-date: C:/Users/17656/Desktop/class/GAMES101/FastMassSpring/b/shaders//basic.vshader
> -- Up-to-date: C:/Users/17656/Desktop/class/GAMES101/FastMassSpring/b/shaders//phong.fshader
> -- Up-to-date: C:/Users/17656/Desktop/class/GAMES101/FastMassSpring/b/shaders//pick.fshader
> -- Configuring done (33.6s)
> -- Generating done (3.2s)
> -- Build files have been written to: C:/Users/17656/Desktop/class/GAMES101/FastMassSpring/b


I performed the next operation.My compiler is reporting a lot of syntax errors about the standard library files, which may be the reason I have something set up wrong, but I can't locate exactly where the error is happening.

> PS C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b> cmake --build .
> 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.0.0+c9eb9dd64
> 版权所有(C) Microsoft Corporation。保留所有权利。
>
> BinaryHelper.cc

> C:\MinGW\include\stdint.h(34,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_dep
> s\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\msvcrtver.h(35,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_
> deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\w32api.h(35,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_dep
> s\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\sdkddkver.h(35,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_
> deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\w32api.h(186,1): warning C4005: “_EXTERN_C”: 宏重定义 [C:\Users\17656\Desktop\class\GAMES101\FastMassSprin
> g\b\_deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\yvals_core.h(1397): message :
>  参见“_EXTERN_C”的前一个定义 [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_deps\openmesh-build\src\OpenMesh\Core\Ope
> nMeshCore.vcxproj]
> C:\MinGW\include\features.h(39,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_d
> eps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(35,9): warning C4068: 未知的杂注“GCC” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_deps\
> openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(398,32): error C2143: 语法错误: 缺少“)”(在“:”的前面) [C:\Users\17656\Desktop\class\GAMES101\FastMassSprin
> g\b\_deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(398,3): error C3861: “__asm__”: 找不到标识符 [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\
> _deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(398,32): error C2143: 语法错误: 缺少“;”(在“:”的前面) [C:\Users\17656\Desktop\class\GAMES101\FastMassSprin
> g\b\_deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(398,32): error C2059: 语法错误:“:” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_deps\op
> enmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(398,52): error C2059: 语法错误:“)” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_deps\op
> enmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(425,17): error C2143: 语法错误: 缺少“)”(在“:”的前面) [C:\Users\17656\Desktop\class\GAMES101\FastMassSprin
> g\b\_deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(424,3): error C3861: “__asm__”: 找不到标识符 [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\
> _deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(425,17): error C2143: 语法错误: 缺少“;”(在“:”的前面) [C:\Users\17656\Desktop\class\GAMES101\FastMassSprin
> g\b\_deps\openmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> C:\MinGW\include\math.h(425,17): error C2059: 语法错误:“:” [C:\Users\17656\Desktop\class\GAMES101\FastMassSpring\b\_deps\op
> enmesh-build\src\OpenMesh\Core\OpenMeshCore.vcxproj]
> 
> 

This is part of the error message, and maybe this is a very newbie problem, but I can't fix it.

**Comment by sam007961** [comment]
There shouldn't be any need to modify the Cmake file, simply provide the OpenGL + GLUT + GLEW locations with the CMAKE_PREFIX_PATH as indicated in the README.

I also see a some error messages referring to Qt and Clang Format, did you include these yourself?
