### ISSUE TITLE
Please provide build instructions

### ISSUE THREAD

**Issue by travis-leith** [sam007961/FastMassSpring#2]
I don't have a much c++ experience (although I do have plenty of experience in other languages).
Building c++ projects has always seemed arcane to me.
That being said, I would like to give this project a try as modelling cloth is involved in a challenge my wife has issued me (she likes to sew).
Please provide step by step build instructions, including which version of VS is required etc.

**Comment by sam007961** [comment]
Hey, Sorry for the late reply! I was using Visual Studio 2015 for this project. If you want to use that, just use the included solution. It uses Nuget for OpenGL dependencies, but you need to have Eigen, GLM and OpenMesh manually installed in the correct locations.

I also just added Cmake integration here #3 to make the build easier. It automatically fetches Eigen, GLM and OpenMesh, but OpenGL, GLEW and GLUT need to be installed manually.

Let me know if you face any problems!

**Comment by sam007961** [comment]
Build instructions added #3 .
