### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Simon-Steinmann** [sam007961/FastMassSpring#4]
Hello,
This repository looks very interesting, but I'm not able to build it. I'm running Ubuntu 18.04 and installed the dependencies mentioned in the Readme.md
I'm not that well versed in c++. I tried my best googling the problems, but I'm stuck. I attached the CMakeFiles folder containing the logs. From what I gather, there is several unknown command lines used. Perhaps a cmake incompatibility? I'm using 3.17

I would really appreciate it, if you could take a look!
[CMakeFiles.zip](https://github.com/sam007961/FastMassSpring/files/5213076/CMakeFiles.zip)

**Comment by sam007961** [comment]
Hi,
It looks like the compiler you are using might be too old. What version of gcc have you configured Cmake to use?

**Comment by Simon-Steinmann** [comment]
I have` gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`
That should not be too old should it?

**Comment by sam007961** [comment]
From the logs, I can see that Cmake is using /usr/bin/cc and /usr/bin/c++ as the compilers. I am not sure if these are just aliases for gcc and g++, but if not then that might be the issue. If so, you have to either fix your PATH environment variable so Cmake can find g++ or manually configure Cmake to use the correct compiler.
