### ISSUE TITLE
Cmake value says GLUT_INCLUDE_DIR-NOTFOUND

### ISSUE THREAD

**Issue by aapatre** [sam007961/FastMassSpring#7]
How do I add the freeglut folder in cmake?

**Comment by sam007961** [comment]
As it says in the readme, you can point cmake to the freeglut folder by adding this flag to the command: `-DCMAKE_PERFIX_PATH:PATH=/path/to/libs`.

**Comment by aapatre** [comment]
Thanks again, will try the manually built approach first...
