### ISSUE TITLE
Getting an error during runtime (probably related to vector): Microsoft C++ exception: std::length_error at memory location 0x0000002A71CFE6E0 

### ISSUE THREAD

**Issue by aapatre** [sam007961/FastMassSpring#9]
Tried to build the code using Visual Studio (didn't use cmake and manually installed stuff) somehow and got these runtime errors in call stack:

![image](https://user-images.githubusercontent.com/20199688/107363426-25021e80-6b00-11eb-9981-8b2ae119bb78.png)

Traces back to these:

Line 1706 in vector:
![image](https://user-images.githubusercontent.com/20199688/107366113-c3dc4a00-6b03-11eb-8434-8804b64f8537.png)

Line 40 in Shader.cpp
![image](https://user-images.githubusercontent.com/20199688/107363492-3f3bfc80-6b00-11eb-9320-d2e7154be321.png)

Line 175 in app.cpp
![image](https://user-images.githubusercontent.com/20199688/107363550-537ff980-6b00-11eb-9651-836acaf4468c.png)

And Line 123 in app.cpp
![image](https://user-images.githubusercontent.com/20199688/107363673-77dbd600-6b00-11eb-9b9c-c440e78b849b.png)

Apologies if these issues are stupid but I'm totally new to opengl, visual studio and cmake 😅

**Comment by sam007961** [comment]
If you are creating the visual studio project manually, you might need to also manually copy the Shaders folder to the build folder.

**Comment by aapatre** [comment]
Thanks a lot, Sam! 😄
